jobs:
  digest:
    name: Acquire digest of the latest image
    outputs:
      llvm: ${{ steps.llvm.outputs.digest }}
    runs-on: ubuntu-latest
    steps:
      - id: llvm
        name: Acquire digest of the latest snowstep/llvm
        run: |
          digest=$(
            curl -s https://hub.docker.com/v2/namespaces/snowstep/repositories/llvm/tags \
              | jq -cr '[.results[]|select(.name=="jammy").images[]|select(.architecture=="amd64")]|max_by(.last_pushed).digest'
          )
          printf 'digest=%s\n' $digest | tee -a $GITHUB_OUTPUT
        shell: bash
  ffmpeg:
    container:
      image: snowstep/llvm@${{ needs.digest.outputs.llvm }}
    name: Build ffmpeg
    needs:
      - digest
      - libraries
    runs-on: ubuntu-latest
    steps:
      - env:
          DEBIAN_FRONTEND: noninteractive
        name: Install dependent packages
        run: |
          apt-fast update
          apt-fast upgrade -y
          apt-fast install --no-install-recommends -y \
            git \
            libass-dev \
            libcaca-dev \
            libdrm-dev \
            libfdk-aac-dev \
            libgl-dev \
            libmp3lame-dev \
            libnuma-dev \
            libopenal-dev \
            libssl-dev \
            libtool \
            libva-dev \
            libvdpau-dev \
            libvorbis-dev \
            make \
            ocl-icd-opencl-dev \
            patch \
            pkg-config \
            yasm
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: /tmp/lib
      - name: Prepare to build
        run: |
          cd /tmp
          {
            echo https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n6.0.tar.gz;
            echo http://www.ladspa.org/download/ladspa_sdk_1.17.tgz;
            echo https://github.com/FFmpeg/nv-codec-headers/archive/refs/tags/n12.0.16.0.tar.gz;
          } | aria2c -i -
          mv ladspa_sdk_1.17.t{,ar.}gz
          for name in FFmpeg-n6.0 ladspa_sdk_1.17 nv-codec-headers-n12.0.16.0; do
            tar -xf /tmp/$name.tar.gz &
          done
          wait
          for name in aom ilbc lzma5 opus sdl2 snappy svtav1 vpx7 webp7 x264 x265; do
            tar -C /usr/local -xvf /tmp/lib/lib$name/lib$name.tar &
          done
          cp ladspa_sdk_1.17/src/ladspa.h /usr/local/include/ &
          {
            cd nv-codec-headers-n12.0.16.0
            make install
            cd ..
          } &
          wait
          rm -frv ladspa_sdk_1.17/ lib/ nv-codec-headers-n12.0.16.0/ *.tar.gz
        shell: bash
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Apply patch
        run: |
          patch --batch --unified /tmp/FFmpeg-n6.0/fftools/ffmpeg.c ffmpeg.patch
      - name: Build
        run: |
          mkdir -pv /tmp/work
          cd /tmp/work
          env PKG_CONFIG_PATH=/usr/local/lib/pkgconfig \
            /tmp/FFmpeg-n6.0/configure \
              --ar=llvm-ar \
              --as=yasm \
              --cc=clang \
              --cxx=clang++ \
              --dep-cc=clang \
              --disable-debug \
              --disable-doc \
              --disable-libxcb \
              --disable-libxcb-shape \
              --disable-libxcb-shm \
              --disable-libxcb-xfixes \
              --disable-sndio \
              --enable-ffplay \
              --enable-gpl \
              --enable-ladspa \
              --enable-libaom \
              --enable-libass \
              --enable-libcaca \
              --enable-libdrm \
              --enable-libfdk-aac \
              --enable-libfreetype \
              --enable-libmp3lame \
              --enable-libopus \
              --enable-libsvtav1 \
              --enable-libvorbis \
              --enable-libvpx \
              --enable-libwebp \
              --enable-libx264 \
              --enable-libx265 \
              --enable-lto \
              --enable-lzma \
              --enable-nonfree \
              --enable-openal \
              --enable-opencl \
              --enable-opengl \
              --enable-shared \
              --enable-version3 \
              --extra-cflags=-march=sandybridge \
              --extra-ldflags="-fuse-ld=lld -march=sandybridge" \
              --extra-version=p1 \
              --ld=clang \
              --prefix=/dist \
              --ranlib=llvm-ranlib \
              --strip=llvm-strip \
              --windres=llvm-windres
            make -j $(nproc)
            make install
      - name: Replace '/dist' with '/usr/local' of pkgconfig
        run: |
          [[ -d /dist/lib/pkgconfig ]] || exit 0
          for name in $(ls /dist/lib/pkgconfig/*.pc); do
            sed -i 's#/dist#/usr/local#g' $name || true
          done
        shell: bash
      - name: Archive the built binaries
        run: |
          tar -C /dist -cf /tmp/ffmpeg.tar .
      - name: Upload the archive
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg
          path: /tmp/ffmpeg.tar
  libraries:
    container:
      image: snowstep/llvm@${{ needs.digest.outputs.llvm }}
    env:
      AR: llvm-ar
      AS: ${{ matrix.as || 'llvm-as' }}
      CC: clang
      CFLAGS: -flto -march=sandybridge
      CXX: clang++
      CXXFLAGS: -flto -march=sandybridge
      LD: clang++
      LDFLAGS: -Wl,--build-id=fast -Wl,--lto-O3 -Wl,--no-gnu-unique -Wl,--thinlto-jobs=all -fuse-ld=lld -march=sandybridge
      NM: llvm-nm
      OBJCOPY: llvm-objcopy
      OBJDUMP: llvm-objdump
      OTOOL: llvm-otool
      RANLIB: llvm-ranlib
      STRIP: ${{ matrix.strip }}
    name: Build ${{ matrix.name }}
    needs:
      - digest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - as: yasm
            cmake: >-
              -DENABLE_DOCS=OFF
              -DENABLE_EXAMPLES=OFF
              -DENABLE_TESTS=OFF
              -DENABLE_TOOLS=OFF
            name: libaom
            ninja: true
            packages: >
              yasm
            repo: https://aomedia.googlesource.com/aom
            strip: llvm-strip
            version: v3.6.1
            workdir: build
          - name: libilbc
            ninja: true
            packages: >
              patch
            patch: CMakeLists.txt libilbc.patch
            repo: https://github.com/TimothyGu/libilbc.git
            strip: llvm-strip
            version: v3.0.4
            workdir: build
          - name: liblzma5
            packages: >
              make
            repo: https://github.com/tukaani-project/xz.git
            strip: llvm-strip
            version: v5.4.4
            workdir: build
          - name: libopus
            ninja: true
            repo: https://github.com/xiph/opus.git
            strip: llvm-strip
            version: v1.4
            workdir: build
          - as: llvm-as
            name: libsdl2
            ninja: true
            packages: >
              libasound2-dev
              libdbus-1-dev
              libdrm-dev
              libegl-dev
              libgbm-dev
              libgl-dev
              libpulse-dev
              libsndio-dev
              libudev-dev
              libwayland-dev
              libx11-dev
              libxext-dev
              libxkbcommon-dev
            repo: https://github.com/libsdl-org/SDL.git
            strip: llvm-strip
            version: release-2.28.2
            workdir: build
          - as: llvm-as
            cmake: >-
              -DSNAPPY_BUILD_BENCHMARKS=OFF
              -DSNAPPY_BUILD_TESTS=OFF
              -DSNAPPY_FUZZING_BUILD=OFF
              -DSNAPPY_REQUIRE_AVX=ON
            name: libsnappy
            ninja: true
            packages: >
              patch
            patch: snappy.cc snappy.patch
            repo: https://github.com/google/snappy.git
            strip: llvm-strip
            version: 1.1.10
            workdir: build
          - as: yasm
            cmake: >-
              -DBUILD_APPS=OFF
              -DBUILD_DEC=OFF
            name: libsvtav1
            ninja: true
            packages: >
              yasm
            repo: https://gitlab.com/AOMediaCodec/SVT-AV1.git
            strip: llvm-strip
            version: v1.5.0
            workdir: build
          - as: yasm
            configure: >-
              --disable-codec-srcs
              --disable-debug-libs
              --disable-docs
              --disable-examples
              --disable-static
              --disable-tools
              --enable-better-hw-compatibility
              --enable-libyuv
              --enable-multi-res-encoding
              --enable-pic
              --enable-postproc
              --enable-shared
              --enable-vp8
              --enable-vp9
              --enable-vp9-highbitdepth
              --enable-vp9-postproc
              --enable-vp9-temporal-denoising
              --enable-webm-io
            name: libvpx7
            ninja: false
            packages:
              libyuv-dev
              make
              yasm
            repo: https://chromium.googlesource.com/webm/libvpx
            strip: strip
            version: v1.13.0
            workdir: work
          - cmake: >-
              -DWEBP_BUILD_CWEBP=OFF
              -DWEBP_BUILD_DWEBP=OFF
              -DWEBP_BUILD_IMG2WEBP=OFF
              -DWEBP_BUILD_WEBPINFO=OFF
              -DWEBP_BUILD_WEBPMUX=OFF
            name: libwebp7
            ninja: true
            repo: https://chromium.googlesource.com/webm/libwebp
            strip: llvm-strip
            version: v1.3.0
            workdir: build
          - as: nasm
            configure: >-
              --disable-avs
              --disable-cli
              --disable-gpac
              --disable-lavf
              --disable-lsmash
              --disable-static
              --disable-swscale
              --enable-shared
              --enable-strip
            name: libx264
            packages: >
              make
              nasm
            repo: https://code.videolan.org/videolan/x264.git
            strip: llvm-strip
            version: master
            workdir: build
          - cmake: >-
              -DENABLE_CLI=OFF
              -DENABLE_LIBNUMA=ON
              -DNATIVE_BUILD=ON
            name: libx265
            ninja: true
            packages: >
              libnuma-dev
            repo: https://bitbucket.org/multicoreware/x265_git.git
            sourcedir: source
            strip: llvm-strip
            version: 3.5
            workdir: work
    steps:
      - env:
          DEBIAN_FRONTEND: noninteractive
        name: Install dependent packages
        run: |
          apt-fast update
          apt-fast upgrade -y
          apt-fast install --no-install-recommends -y \
            cmake \
            git \
            libtool \
            pkg-config \
            ${{ (matrix.ninja && 'python3-pip') || '' }} \
            ${{ matrix.packages }}
      - if: ${{ matrix.ninja }}
        run: |
          pip install --upgrade pip
          pip install ninja
      - name: Clone the repository
        run: |
          git clone --depth 1 \
                    --recursive \
                    --single-branch \
                    -b ${{ matrix.version }} \
                    ${{ matrix.repo }} \
                    /tmp/source
      - if: ${{ matrix.patch }}
        name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - if: ${{ matrix.patch }}
        name: Apply patch
        run: |
          patch --batch --unified /tmp/source/${{ matrix.patch }}
      - if: ${{ matrix.configure != '' }}
        name: Build ${{ matrix.name }}
        run: |
          mkdir -pv /tmp/source/${{ matrix.workdir }}
          cd /tmp/source/${{ matrix.workdir }}
          ../configure \
            ${{ matrix.configure }} \
            --prefix=/dist
          make -j $(nproc)
          make install
      - if: ${{ matrix.configure == '' }}
        name: Build ${{ matrix.name }}
        run: |
          mkdir -pv /tmp/source/${{ matrix.workdir }}
          cd /tmp/source/${{ matrix.workdir }}
          cmake \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/dist \
            ${{ matrix.cmake }} \
            -G "${{ (matrix.ninja && 'Ninja') || 'Unix Makefiles' }}" \
            ../${{ matrix.sourcedir }}
          cmake --build .
          cmake --install .
      - name: Replace '/dist' with '/usr/local' of pkgconfig
        run: |
          [[ -d /dist/lib/pkgconfig ]] || exit 0
          for name in $(ls /dist/lib/pkgconfig/*.pc); do
            sed -i 's#/dist#/usr/local#g' $name || true
          done
        shell: bash
      - if: ${{ matrix.name == 'libilbc' }}
        name: Rename libilbc.pc
        run: |
          mv -v /dist/lib/pkgconfig/{lib,}ilbc.pc
        shell: bash
      - if: ${{ matrix.name == 'libsnappy' }}
        name: Generate snappy.pc
        run: |
          mkdir -pv /dist/lib/pkgconfig
          {
            echo prefix=/usr/local
            echo exec_prefix=\$\{prefix\}
            echo includedir=\$\{prefix\}/include
            echo libdir=\$\{prefix\}/lib
            echo
            echo Name: Snappy
            echo Description: A fast compression/decompression library
            echo Version: ${{ matrix.version }}
            echo Libs: -L\$\{libdir\} -lsnappy
            echo Cflags: -I\$\{includedir\}
          } > /dist/lib/pkgconfig/snappy.pc
      - name: Archive the build binaries
        run: |
          tar --group=root \
              --owner=root \
              -C /dist \
              -cf /tmp/${{ matrix.name }}.tar \
              .
      - name: Upload the archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: /tmp/${{ matrix.name }}.tar
name: Build
on:
  workflow_dispatch:
